version: "3"

services:
  mysql:
    container_name: mysql
    platform: linux/x86_64 # M1チップ対応
    image: mysql:5.7
    restart: always
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: tiffin
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "-uuser", "-ppassword", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
